# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 93e469aaec50c4b63d18ab0f46182ede638af3b1a81bf60ec1ac9c3f7e071da06f399eef342ea86ebf7241aea79eb053ef293d11a92ce9cccb18922ed72cf143

test:
  secret_key_base: 777ceef1127cff331ff870885daf256da29c8aada186da37d71b83b36fe6e874d2992e07c5df88bf3bd2ea7286848c419159953401b6f25f6238c0d0c0026ca3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
